quarkus:
  datasource:
    db-kind: h2
    username: sa
    password:
    jdbc:
      url: jdbc:h2:mem:school

  hibernate-orm:
    log:
      sql: true
    database:
      generation: drop-and-create